name: Github Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@latest

    - name: Set up JDK
      uses: actions/setup-java@latest
      with:
        java-version: '11'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          *.jar
